### ISSUE TITLE
Specifying host in application.yml causes tests to fail

### ISSUE THREAD

**Issue by yallara** [micronaut-projects/micronaut-test#237]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem available from lauch.micronaut.io
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use launch.micronaut.io to create a sample Application: Java 11, version 2.0.1, Groovy, Gradle, Spock (though the same steps applied to `complete` under https://github.com/micronaut-guides/creating-your-first-micronaut-app.git also failed)
2. Run ./gradlew test and confirm all tests pass
3. Edit application.yml, and set micronaut.server.host to 127.0.0.1
4. Run ./gradlew test, tests fail
5. ./gradlew run works as expected at all times

```
DemoSpec > test it works FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at DemoSpec.groovy:16
```

When I hit this problem in my own project, the error message had more detail:

```
BaticaSpec > test it works FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at BaticaSpec.groovy:16
11:49:57.067 batica-test [Test worker] ERROR i.m.h.server.netty.NettyHttpServer - Unable to start server. Port already 8084 in use.

Unable to start Micronaut server on port: 8084
io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8084
	at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:488)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:309)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:110)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:227)
	at io.micronaut.test.extensions.spock.MicronautSpockExtension.lambda$visitSpecAnnotation$3(MicronautSpockExtension.java:84)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:136)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

And my other tests all failed with (in my project I'm also setting micronaut.server.port)

```
ERROR i.m.h.server.netty.NettyHttpServer - Unable to start server. Port already 8084 in use.
```

### Expected Behaviour

Setting micronaut.server.host should not affect success or otherwise of tests.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

### Workaround
Set micronaut.server.host to 0.0.0.0 in application-test.yml

**Comment by alvarosanchez** [comment]
This is something specific to your machine where port 8084 is already used, possibly because you have a leftover instance of the same application running.

**Comment by yallara** [comment]
That "answer" raises several questions. First, what does port 8084 have to do with the Steps to Reproduce?

Second is how can a port already be in use when micronaut.server.host is set, and magically not in use when it isn't set?

Third, how come my system doesn't know the port is in use?

Fourth, how come I get the same behaviour on Gitlab's CI pipeline? What do you propose is already using a port on a newly created docker instance, and only when micronaut.server.host is set?

And finally, are you saying you tried on your own computer and couldn't reproduce? Here's a record of a session, using the zip from launch.micronaut.io as described in my Steps to Reproduce. Maybe it will shed some light on why your system is different to the others (I also tried it on the server on which I run java webapps, and it had the same behaviour: that's 3 very different systems with identical behaviour, one of them a commercial CI pipeline).

```
~/code/micronaut/testtest2$ ss -alt
State                      Recv-Q                     Send-Q                                          Local Address:Port                                            Peer Address:Port                     
LISTEN                     0                          5                                                   127.0.0.1:7200                                                 0.0.0.0:*                        
LISTEN                     0                          80                                                  127.0.0.1:mysql                                                0.0.0.0:*                        
LISTEN                     0                          2                                                     0.0.0.0:44851                                                0.0.0.0:*                        
~/code/micronaut/testtest2$ ./gradlew test

BUILD SUCCESSFUL in 9s
4 actionable tasks: 4 executed
~/code/micronaut/testtest2$ ss -alt
State                     Recv-Q                     Send-Q                                              Local Address:Port                                          Peer Address:Port                    
LISTEN                    0                          5                                                       127.0.0.1:7200                                               0.0.0.0:*                       
LISTEN                    0                          80                                                      127.0.0.1:mysql                                              0.0.0.0:*                       
LISTEN                    0                          2                                                         0.0.0.0:44851                                              0.0.0.0:*                       
LISTEN                    0                          50                                             [::ffff:127.0.0.1]:40583                                                    *:*                       
~/code/micronaut/testtest2$ (edit application.yml)
~/code/micronaut/testtest2$ cat src/main/resources/application.yml
micronaut:
  application:
    name: demo
  server:
    host: 127.0.0.1
~/code/micronaut/testtest2$ ./gradlew test

> Task :test FAILED

DemoSpec > test it works FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at DemoSpec.groovy:16

1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/anne/code/micronaut/testtest2/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
4 actionable tasks: 3 executed, 1 up-to-date
~/code/micronaut/testtest2$ ss -alt
State                     Recv-Q                     Send-Q                                              Local Address:Port                                          Peer Address:Port                    
LISTEN                    0                          5                                                       127.0.0.1:7200                                               0.0.0.0:*                       
LISTEN                    0                          80                                                      127.0.0.1:mysql                                              0.0.0.0:*                       
LISTEN                    0                          2                                                         0.0.0.0:44851                                              0.0.0.0:*                       
LISTEN                    0                          50                                             [::ffff:127.0.0.1]:40583                                                    *:*                       
~/code/micronaut/testtest2$ (edit application.yml)
~/code/micronaut/testtest2$ cat src/main/resources/application.yml
micronaut:
  application:
    name: demo
~/code/micronaut/testtest2$ ./gradlew test

BUILD SUCCESSFUL in 2s
4 actionable tasks: 3 executed, 1 up-to-date

```

**Comment by alvarosanchez** [comment]
You are suggesting that Micronaut applications will fail to bind a port on 127.0.0.1:8084 in all computers, which would be very surprising. In fact it simply isn't true.

> First, what does port 8084 have to do with the Steps to Reproduce?

It has to do with the exception messages:

* `io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8084`.
* `Caused by: java.net.BindException: Address already in use`.

> Second is how can a port already be in use when micronaut.server.host is set, and magically not in use when it isn't set?

I can't answer that question without knowing what is running in your computer.

> Third, how come my system doesn't know the port is in use?

I am on MacOS and there is no `ss` in Mac, so can't tell what it does. Try with `netstat -an | grep LISTEN`

> Fourth, how come I get the same behaviour on Gitlab's CI pipeline?

No idea, but the steps to reproduce the issue don't manifest the problem. Also, you mentioned you are fixing the port by setting `micronaut.server.port` (I'm guessing to 8084)

> And finally, are you saying you tried on your own computer and couldn't reproduce?

Of course I did.

**Comment by yallara** [comment]
Port 8084:

The exception message was NOT from the Steps to Reproduce demo project. Port was not set in those steps. The simple reproducible steps did not set or in any way alter any port. The exception report was from a different project, which had more logging enabled. I included that exception report only because it had a stacktrace that I thought might assist you, despite the risk that it isn't relevant.

netstat vs ss:

netstat is the old utility that has been superseded by ss on Linux. In other words, ss is my system's newer equivalent to netstat. The options I used say to show listening TCP sockets (despite a spurious 'a' option I included).

Fixing the problem:

No, I didn't change the port to fix the problem. In the demo project, port was at no time set by me, ever. As far as I can tell, the port is completely irrelevant to this issue. I have to remove the host setting I added (adding the host setting is THE ONLY change I made to the demo project from launch.micronaut.io), or change it from 127.0.0.1 to 0.0.0.0, for the test to be successful.

Reproducibility:

I was thinking you hadn't tried to reproduce, because your reply fixated on a non-existent port setting. I'm still puzzled why you think a port setting is relevant given you never touched it, but at least we know the problem is Linux-specific.

I don't have access to anything other than Linux systems (and Docker). So Linux-specific problems become very difficult to track down, given I have no familiarity with the code. I'll try to learn more with the help of a debugger, but unless I get lucky it may be a while before I can report back.

**Comment by ilopmar** [comment]
@yallara I'm running Linux and I've tried the following things after defining the property `micronaut.server.host: 127.0.0.1`:

- Run the tests in the guide as it is with both Java 8 and Java 11
- Update the guide to Micronaut 2.0.1

In all the cases the tests always pass.

Some random thoughts and things to try:
- Do you have any firewall enabled that can be doing something tricky?
- Do you have some environment variable that can set the micronaut port to that value?
- Can you run `nc -l 127.0.0.1 8084` just to make sure that you are able to bind a process to that ip and port?

If you have more information, please do share it. We would like to help you to fix the issue, but we need some way of reproducing it and, at this moment, we can't.

**Comment by alvarosanchez** [comment]
@yallara can you share a Docker image where the problem reproduces?

**Comment by yallara** [comment]
As promised, it took me a while to get back to this project. And the good news is, whatever was causing the problem, it's fixed in micronaut 2.0.3.

I created a docker container and used the latest demo download from launch.micronaut.io, which includes micronaut 2.0.3. And I could not reproduce the problem. But when I replace the 2.0.3 demo download in docker with my previously downloaded 2.0.1 demo zip, the problem does occur.

Seeing 2.0.3 fixes this, I won't bother sharing my docker test setup.

So you can mark this as fixed in 2.0.3. I never tried 2.0.2, so no idea whether it worked or not then.
